# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'cotaja_rn' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )


  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        existing_flags = config.build_settings['OTHER_CFLAGS'] || '$(inherited)'
        config.build_settings['OTHER_CFLAGS'] = "#{existing_flags} -Wno-deprecated-declarations -Wno-error=deprecated-declarations -Wno-error=return-type -Wno-return-type -Wno-deprecated-objc-isa-usage -Wno-error=deprecated-objc-isa-usage"
        existing_cxxflags = config.build_settings['OTHER_CXXFLAGS'] || '$(inherited)'
        config.build_settings['OTHER_CXXFLAGS'] = "#{existing_cxxflags} -Wno-deprecated-declarations -Wno-error=deprecated-declarations -Wno-error=return-type -Wno-return-type -Wno-deprecated-objc-isa-usage -Wno-error=deprecated-objc-isa-usage"
        config.build_settings['CLANG_WARN_DEPRECATED_OBJC_ISA_USAGE'] = 'NO'
        config.build_settings['CLANG_WARN_RETURN_TYPE'] = 'YES'
        config.build_settings['GCC_WARN_ABOUT_RETURN_TYPE'] = 'YES'
        config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
        config.build_settings['SWIFT_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
        config.build_settings['SWIFT_VERSION'] = '5.0'
      end
    end
  end
end
